### ISSUE TITLE
Direct m.me links to sequences need the "Getting started button"

### ISSUE THREAD

**Issue by flexgrip** [FunnelDash/funnel-builder#54]
In order to use m.me/{page_id}?ref={widget_id} and potentially QR codes, a user's page's messenger settings needs to have the "Getting started" button from facebook installed. Otherwise it won't work. 

This means if someone creates a funnel with one of these types of triggers, we'll need to add that button for them.

On the front-end, you'll need to ping an endpoint in the app (that doesn't exist yet), to create the getting started button. 

When the getting started button is clicked, it automatically delivers a pre-scripted message that is saved in facebook. After that, a postback is fired to the bot and the user is subscribed. Pain in the ass...

**Comment by donomans** [comment]
this was done - getting started call is happening
